# Generated by Django 5.2.4 on 2025-08-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_type", models.CharField(max_length=50)),
                ("case_number", models.CharField(max_length=50)),
                ("filing_year", models.CharField(max_length=4)),
                ("raw_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
